#
# Copyright (C) 2020-2024 Lin Song <linsongui@gmail.com>
#
# This work is licensed under the Creative Commons Attribution-ShareAlike 3.0
# Unported License: http://creativecommons.org/licenses/by-sa/3.0/
#
# Attribution required: please include my name in any derivative and let me
# know how you have improved it!

name: build cron

on:
  schedule:
    - cron: '40 2,14 * * *'

jobs:
  check_update:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/check_update.yml
    with:
      os_type: alpine
    secrets:
      CACHE_NAME: ${{ secrets.CACHE_NAME2 }}

  vpn_test:
    needs: check_update
    if: needs.check_update.outputs.should_test == 'true'
    uses: ./.github/workflows/vpn_test.yml
    with:
      os_type: alpine

  buildx:
    needs: [check_update, vpn_test]
    if: needs.check_update.outputs.should_update == 'true'
    uses: ./.github/workflows/buildx.yml
    with:
      os_type: alpine
    secrets:
      CACHE_NAME: ${{ secrets.CACHE_NAME2 }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      BUILD_ONLY: ${{ secrets.BUILD_ONLY }}
